name: jbt
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  firebase_storage: ^8.0.1
  firebase_core: ^1.0.2
  image_picker: ^0.7.4
  flutter_svg: ^0.19.1
  provider: ^5.0.0
  recase: ^3.0.1
  multi_image_picker: ^4.8.0
  intl: ^0.17.0
  path_provider: ^2.0.1
  flutter_absolute_path: ^1.0.6
  mask_text_input_formatter: ^1.2.1
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.0.5
  dio: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Light.ttf
          weight: 300  

  assets:
    - assets/icon-deselected-map.png
    - assets/icon-deselected-noti.png
    - assets/icon-deselected-setting.png
    - assets/icon-selected-map.png
    - assets/icon-selected-noti.png
    - assets/icon-selected-setting.png
    - assets/icon-password.png
    - assets/icon-username.png
    - assets/icon-username2.png
    - assets/icon.png
    - assets/button-image-picker.png